### PR TITLE
Fixes for new version of rxode2()<-

### LINKED ISSUE #31: Simply remove the `$fun` and `addEta()` would retain whatever it needs to retain
Simply remove the `$fun` and it wold retain whatever it needs to retain, actually.  But it would be a full rxode2 ui object (I'm unsure why you only wanted to return the function here).

_Originally posted by @mattfidler in https://github.com/nlmixr2/rxode2/issues/439#issuecomment-1445266844_

### PR DESCRIPTION
**Pull request by mattfidler**
Closes #31

### CODE REVIEW

**Comment by billdenney** [comment]
Does it need all of the re-exports or can it just use `rxode2::someFun()`?

**Comment by mattfidler** [comment]
Not sure.  You can try whatever you want here.

**Comment by mattfidler** [comment]
The check works for me, so I will be on the path to submitting everything.

**Comment by billdenney** [comment]
Sounds good.  The current version should work with the old and new versions of rxode2, while this PR will improve it for the new version.  I'll work on this and submit it after the new rxode2 is on CRAN.

**Comment by mattfidler** [comment]
Now `nlmixr2lib` no longer works and needs this to be compatible with the `nlmixr2est` library.

**Comment by billdenney** [comment]
I will push this to CRAN in the next day or two.

**Pull request merged**
