### PR TITLE
Move convertMM

### PR DESCRIPTION
**Pull request by mattfidler**

### CODE REVIEW

**Comment by mattfidler** [comment]
This works for me @billdenney .

If you are ok with it you can merge it.

**Comment by mattfidler** [comment]
The only cases that are not handled is:
-  `linCmt()`  
- `d/dt(central) = - (cl/v) * central` types of paramterizations.

To do `linCmt()` I need:

- degrade `linCmt()` to ODE
- Then this would work, but I think it

**Comment by mattfidler** [comment]
I'm unsure if you want to align input arguments.  Some functions have `model` instead of `ui`

**Comment by mattfidler** [comment]
Also could add labels to `lvm` and `lkm`, I guess or add initial estimates

**Comment by billdenney** [comment]
It looks good to me.  FYI, you could have the function of `.replaceMult` with `formulops::modify_formula`.  (No need to change it now.)

**Pull request merged**
