### PR TITLE
A nonworking prototype for addBioavailability()

### PR DESCRIPTION
**Pull request by billdenney**

### CODE REVIEW

**Comment by mattfidler** [comment]
This is likely too complex.

Currently `%>% model(f(depot) <- ldepot)` will already add it in the "correct" place.  For the linear compartment model it can be added anywhere (though it could be modified to add before the `linCmt()` statement.

**Comment by mattfidler** [comment]
This is also true of all the other compartment-based parameters, `lag`, `rate` and `dur` as well as initial conditions `x(0)`.

**Comment by mattfidler** [comment]
This is now included in the addTransit branch...

**Comment by mattfidler** [comment]
That is at least the `addBioavailability()`

**Comment by billdenney** [comment]
Thanks, I'll close this PR then.

**Pull request closed without merging**
