### PR TITLE
Added model attributes

### PR DESCRIPTION
**Pull request by john-harrold**
The documentation was updated to include
- Dosing compartments
- Units (time and dosing)
- A depends field for models that are intended to be built upon other models

The model database table (modeldb) was updated to include:
- A column indicating if a solved model has been used (linCmt)
- Dosing states (similar to how parameters are currently used)
- Depends (similar to how parameters are currently being used)

I updated the tests to correct some hard references to list positions that were shifted when I updated the model R scripts in inst.

### CODE REVIEW

**Comment by billdenney** [comment]
Thanks for creating this.  A few thoughts:

1. I see "linCmt" as a special case of algebraic solutions.  It is an important special case for nlmixr2.  That said, would it make sense to call it "algebraic" so that a generic Emax model could also be true?  (I'm open to either position here, it just struck me as specific.)
2. I think that you can autogenerate the depends column based on the covariate list from the model.  Is it doing something else?  If not, I would suggest replacing it with the covariate list.

**Comment by john-harrold** [comment]
My main motivation here is to be able to include the model library in ruminate to do rule-based dosing. To do that I need a couple things. I cannot stop and start models that have solved components, only with ODEs. So I added that column to allow me to filter the modeldb based on that. The way I'm picking it up is using the params field of the model object. It's not a user specified model attribute. See the example in this comment:

https://github.com/nlmixr2/nlmixr2lib/issues/69#issuecomment-2168232459

I don't know of a way to detect a purely algebraic model. If you do, I'm happy to do that because it would make it more generalizable. 

I need the pieces feeding in from other models separately from the covariates. I want to allow users to select models as base models to build on them. So I need to know if the model has something other than covariates to exclude it from being a base model. And then I want to take the elements of the current model and see if they satisfy the depends for others to allow them to be stacked/piped together.

**Comment by mattfidler** [comment]
>  I don't know of a way to detect a purely algebraic model. If you do, I'm happy to do that because it would make it more generalizable.

Yes there is:

``` r
library(rxode2)
#> Warning: package 'rxode2' was built under R version 4.3.3
#> rxode2 2.1.3 using 4 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
```

``` r
mod <- function() {
  ini({
    e0 <- 0.1
    em <- 10
    e50 <- 20
    err.sd <- 0.1
  })
  model({
    ef <- e0 + (em - e0) * time / (time + e50)
    ef ~ add(err.sd)
  })
}

mod <- mod()

!mod$params$linCmt && (length(mod$params$cmt)  == 0)
#> [1] TRUE
```

``` r

mod <- function() {
  ini({
    ka <- 1
    cl <- 0.1
    vc <- 4
    err.sd <- 0.1
  })
  model({
    Cc <- linCmt(ka, cl, vc)
    Cc ~ add(err.sd)
  })
}

mod <- mod()

!mod$params$linCmt && (length(mod$params$cmt)  == 0)
#> [1] FALSE
```

``` r

mod <- function() {
  ini({
    cl <- 0.1
    vc <- 4
    err.sd <- 0.1
  })
  model({
    d/dt(central) <- -central * cl / vc
    Cc <- central / vc
    Cc ~ add(err.sd)
  })
}

mod <- mod()

!mod$params$linCmt && (length(mod$params$cmt)  == 0)
#> [1] FALSE
```

<sup>Created on 2024-06-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>


Also found  and fixed a bug with this regexp, could be triggered by your project

https://github.com/nlmixr2/rxode2/pull/697

**Comment by john-harrold** [comment]
Thankyou Matt. Bill let me know if there is anything else you'd like for me to change? I can make changes that take what Matt described above into account, and I can add a column called algebraic. 

@mattfidler is it possible to have linCmt() used with ODES?

**Comment by mattfidler** [comment]
Yes.  It is possible though not well tested

**Comment by john-harrold** [comment]
But the mod$params$linCmt field will be TRUE if that is the case?

**Comment by mattfidler** [comment]
Yes.

**Comment by billdenney** [comment]
Given these suggestions, maybe there should be two columns.  One could be "ode" and one "linCmt".  Then, all the information is there to use.

The only other change would be to fix the CodeFactor issues, please.

Other than that, I think we're good.

**Comment by john-harrold** [comment]
Yeah I was going to try and address the code factor issues. Is it because I'm using c() with a single element?

**Comment by billdenney** [comment]
Yeah, that's it.

**Comment by john-harrold** [comment]
One other question. Should a model be flagged as algebraic if it has no ODES or if it has no ODES and no linCmt()?

**Comment by billdenney** [comment]
To me, if it has no ODEs, it's algebraic because linCmt is also an algebraic solution.

**Comment by mattfidler** [comment]
> To me, if it has no ODEs, it's algebraic because linCmt is also an algebraic solution.

Well to me the difference between `linCmt` and algebraic is the ability to dose the central and depot compartments, so I think they are a bit different.

**Comment by john-harrold** [comment]
I think the two of you can see why I'm going back and forth on this :). If the column reflects algebraic only then you can just filter where either the algebraic or linCmt columns are TRUE to get what Bill wants. If the column reflects strictly algebraic with or without linCmt() then we can isolate algebraic only systems by looking where the algebraic column is TRUE and the linCmt column is FALSE.

 I'm actually OK either way :)

**Comment by john-harrold** [comment]
Ok I had to make a command decision so I can move on in life :). I went with Matts suggestion. So linCmt() is true if there are any linCmt() commands. And the algebraic column is only true for purely algebraic (no linCmt() and no ODEs) models.

**Comment by billdenney** [comment]
That works.  :)

To me, there are two states to define which may overlap:

* linCmt or not
* ODE or algebraic

As long as these are possible to detect, then I'm good with whatever solution is proposed.

I'll review the code now.

**Comment by billdenney** [comment]
Looks good to me!

**Pull request merged**
